import "../styles/globals.css"
import "../styles/pages.scss"

import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {/* <div>Route Groups配下用に任意のレイアウトを作成してください</div> */}
    </>
  )
}
